# yaml-language-server: $schema=https://json.schemastore.org/github-issue-forms.json

name: Documentation
title: Documentation
description: Add documentation
labels: [documentation]
assignees: haras-unicorn
body:
  - type: textarea
    attributes:
      label: Area
      description: |
        Area of the documentation that needs to be updated.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Description
      description: |
        Description of the documentation that needs to be updated.
    validations:
      required: true
